name: Deploy React web on Commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build Atnire YAML
      run: |
        cd atnire-yaml
        npm install
        npm run build

    - name: Upload Atnire YAML to GitHub Pages
      uses: actions/upload-artifact@v2
      with:
        name: atnire-yaml
        path: atnire-yaml/dist

    - name: Deploy Atnire YAML to GitHub Pages
      uses: actions/deployment@v3
      with:
        repository: '${{ github.repository }}'
        token: '${{ secrets.GITHUB_TOKEN }}'
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
        targets: atnire-yaml
