name: Deploy on Commit

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Configure Git identity
      run: |
        git config --global user.email "victorasenj@gmail.com"
        git config --global user.name "victor-asenjo"

    - name: Authenticate with GitHub
      run: |
        git remote add origin-with-token https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git

    - name: Run deploy script
      run: npm run deploy
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Confirmation
      run: echo "🎉 The job was automatically triggered."
